export const triviaQuestions = [
  {
    id: "Q001",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso gouda o cheddar?",
    options: ["Kill Bill", "Cheddar plancha", "Burger básica", "La limeña"],
    answer: "C",
    explanation: "La respuesta correcta es Burger básica.",
  },
  {
    id: "Q002",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso gouda, lechuga, tomate, cebolla morada y huevo frito?",
    options: ["Burger del mes", "Burger completa", "Burger básica", "Azul ruibarbo"],
    answer: "B",
    explanation: "La respuesta correcta es Burger completa.",
  },
  {
    id: "Q003",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso cheddar, tocino, huevo frito, pepinillos y salsa BBQ?",
    options: ["La limeña", "Azul ruibarbo", "La 36", "Clásica BBQ"],
    answer: "D",
    explanation: "La respuesta correcta es Clásica BBQ.",
  },
  {
    id: "Q004",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye camarones al limón y palta trozada?",
    options: ["La 420", "Veggie Thai", "Camarones al limón", "Kill Bill"],
    answer: "C",
    explanation: "La respuesta correcta es Camarones al limón.",
  },
  {
    id: "Q005",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye mix de ajíes y nachos?",
    options: ["Camarones al limón", "Nachos", "Burger completa", "Doble cuarto libra queso"],
    answer: "B",
    explanation: "La respuesta correcta es Nachos.",
  },
  {
    id: "Q006",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye aros de cebolla apanados y salsa BBQ?",
    options: ["Gouda frito", "Burger Factory", "Veggie Thai", "BBQ tocino"],
    answer: "D",
    explanation: "La respuesta correcta es BBQ tocino.",
  },
  {
    id: "Q007",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye burger veggie de garbanzos, cebollín grillado, palta y pepinillos?",
    options: ["Doble cuarto libra queso", "Burger del mes", "La 420", "Burger Factory"],
    answer: "C",
    explanation: "La respuesta correcta es La 420.",
  },
  {
    id: "Q008",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye tocino, lechuga y tomate?",
    options: ["La 420", "Provoleta", "BLT", "Gouda frito"],
    answer: "C",
    explanation: "La respuesta correcta es BLT.",
  },
  {
    id: "Q009",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye 2 burgers y medallón de queso crocante?",
    options: ["La tocinetta", "Burger básica", "Veggie Thai", "Doble cuarto libra queso"],
    answer: "D",
    explanation: "La respuesta correcta es Doble cuarto libra queso.",
  },
  {
    id: "Q010",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye provoleta, huevo y morrón?",
    options: ["Nachos", "Provoleta", "Burger básica", "BLT"],
    answer: "B",
    explanation: "La respuesta correcta es Provoleta.",
  },
  {
    id: "Q011",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye provoleta grillada, morrón, champignones y cebolla caramelizada?",
    options: ["Burger básica", "Camarones al limón", "Vegetariana", "La limeña"],
    answer: "C",
    explanation: "La respuesta correcta es Vegetariana.",
  },
  {
    id: "Q012",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso azul y salsa BBQ con ruibarbo?",
    options: ["Burger básica", "Nachos", "Clásica BBQ", "Azul ruibarbo"],
    answer: "D",
    explanation: "La respuesta correcta es Azul ruibarbo.",
  },
  {
    id: "Q013",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso cheddar, cebolla a la plancha y huevo frito?",
    options: ["La gran S", "Cheddar plancha", "La 36", "Los tres chanchitos"],
    answer: "B",
    explanation: "La respuesta correcta es Cheddar plancha.",
  },
  {
    id: "Q014",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso gouda, cebolla caramelizada, tocino y huevo frito?",
    options: ["Cheddar plancha", "Club Veggie", "La 420", "Gouda frito"],
    answer: "D",
    explanation: "La respuesta correcta es Gouda frito.",
  },
  {
    id: "Q015",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye tocino crocante, chutney de tocino, chocobacon y tocinesa?",
    options: ["La limeña", "BBQ tocino", "Burger Factory", "La tocinetta"],
    answer: "D",
    explanation: "La respuesta correcta es La tocinetta.",
  },
  {
    id: "Q016",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso crema, camarones envueltos en tocino y salsa ginzoo?",
    options: ["Kill Bill", "La limeña", "Burger del mes", "La 36"],
    answer: "A",
    explanation: "La respuesta correcta es Kill Bill.",
  },
  {
    id: "Q017",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso cheddar, tocino, palta trozada y huevo frito?",
    options: ["Burger completa", "Burger Factory", "Los tres chanchitos", "La gran S"],
    answer: "D",
    explanation: "La respuesta correcta es La gran S.",
  },
  {
    id: "Q018",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso gouda, queso azul, cebolla caramelizada y champignones?",
    options: ["La limeña", "BLT", "BBQ tocino", "La Francesa"],
    answer: "D",
    explanation: "La respuesta correcta es La Francesa.",
  },
  {
    id: "Q019",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso cheddar, tocino, aros de cebolla, pepinillos y salsa BBQ?",
    options: ["La gran S", "Los tres chanchitos", "Burger del mes", "La 36"],
    answer: "D",
    explanation: "La respuesta correcta es La 36.",
  },
  {
    id: "Q020",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye tocino, pulled pork, longaniza y salsa BBQ?",
    options: ["Azul ruibarbo", "Los tres chanchitos", "La tocinetta", "La 36"],
    answer: "B",
    explanation: "La respuesta correcta es Los tres chanchitos.",
  },
  {
    id: "Q021",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso crema, ceviche de camarón, mix de ajíes y tortilla de maíz?",
    options: ["La limeña", "La 36", "Burger Factory", "Burger básica"],
    answer: "A",
    explanation: "La respuesta correcta es La limeña.",
  },
  {
    id: "Q022",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye queso cheddar, lechuga, tomate, pepinillos y salsa club?",
    options: ["Gouda frito", "Camarones al limón", "Club Veggie", "Burger básica"],
    answer: "C",
    explanation: "La respuesta correcta es Club Veggie.",
  },
  {
    id: "Q023",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye garbanzos, champignones, mix de ajíes, salsa ginzoo y limón?",
    options: ["Veggie Thai", "Doble cuarto libra queso", "Clásica BBQ", "Vegetariana"],
    answer: "A",
    explanation: "La respuesta correcta es Veggie Thai.",
  },
  {
    id: "Q024",
    category: "Burgers",
    difficulty: "Fácil/Media",
    question: "¿Cuál producto de la carta incluye base, salsa y extras a elección?",
    options: ["Burger completa", "La gran S", "Camarones al limón", "Burger Factory"],
    answer: "D",
    explanation: "La respuesta correcta es Burger Factory.",
  },
  {
    id: "Q025",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Burger básica?",
    options: ["$10.600", "$9.800", "$10.900", "$8.200"],
    answer: "D",
    explanation: "Burger básica aparece en la carta con precio $8.200.",
  },
  {
    id: "Q026",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Burger completa?",
    options: ["$9.600", "$8.200", "$11.800", "$10.800"],
    answer: "A",
    explanation: "Burger completa aparece en la carta con precio $9.600.",
  },
  {
    id: "Q027",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Clásica BBQ?",
    options: ["$10.900", "$9.800", "$12.800", "$9.500"],
    answer: "A",
    explanation: "Clásica BBQ aparece en la carta con precio $10.900.",
  },
  {
    id: "Q028",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Doble cuarto libra queso?",
    options: ["$6.700", "$9.500", "$13.600", "$12.800"],
    answer: "C",
    explanation: "Doble cuarto libra queso aparece en la carta con precio $13.600.",
  },
  {
    id: "Q029",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Provoleta?",
    options: ["$9.500", "$11.800", "$6.700", "$12.500"],
    answer: "D",
    explanation: "Provoleta aparece en la carta con precio $12.500.",
  },
  {
    id: "Q030",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Kill Bill?",
    options: ["$9.800", "$10.600", "$9.600", "$12.800"],
    answer: "D",
    explanation: "Kill Bill aparece en la carta con precio $12.800.",
  },
  {
    id: "Q031",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de La tocinetta?",
    options: ["$9.500", "$11.800", "$10.800", "$10.900"],
    answer: "C",
    explanation: "La tocinetta aparece en la carta con precio $10.800.",
  },
  {
    id: "Q032",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de La gran S?",
    options: ["$10.900", "$13.600", "$9.800", "$11.800"],
    answer: "D",
    explanation: "La gran S aparece en la carta con precio $11.800.",
  },
  {
    id: "Q033",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Los tres chanchitos?",
    options: ["$10.800", "$12.500", "$9.500", "$10.900"],
    answer: "B",
    explanation: "Los tres chanchitos aparece en la carta con precio $12.500.",
  },
  {
    id: "Q034",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Burger Factory?",
    options: ["$10.500", "$6.700", "$12.800", "$12.500"],
    answer: "B",
    explanation: "Burger Factory aparece en la carta con precio $6.700.",
  },
  {
    id: "Q035",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Azul ruibarbo?",
    options: ["$11.800", "$10.500", "$9.800", "$6.700"],
    answer: "C",
    explanation: "Azul ruibarbo aparece en la carta con precio $9.800.",
  },
  {
    id: "Q036",
    category: "Precios Burgers",
    difficulty: "Media",
    question: "¿Cuál es el precio de Gouda frito?",
    options: ["$9.600", "$6.700", "$10.600", "$9.500"],
    answer: "C",
    explanation: "Gouda frito aparece en la carta con precio $10.600.",
  },
  {
    id: "Q037",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B15?",
    options: ["La tocinetta", "Club Veggie", "Burger básica", "Los tres chanchitos"],
    answer: "A",
    explanation: "El código B15 corresponde a La tocinetta.",
  },
  {
    id: "Q038",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B19?",
    options: ["Club Veggie", "La gran S", "La Francesa", "La 36"],
    answer: "D",
    explanation: "El código B19 corresponde a La 36.",
  },
  {
    id: "Q039",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B18?",
    options: ["BLT", "Burger Factory", "La Francesa", "Clásica BBQ"],
    answer: "C",
    explanation: "El código B18 corresponde a La Francesa.",
  },
  {
    id: "Q040",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B23?",
    options: ["Kill Bill", "La tocinetta", "Veggie Thai", "Burger del mes"],
    answer: "D",
    explanation: "El código B23 corresponde a Burger del mes.",
  },
  {
    id: "Q041",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B13?",
    options: ["Burger básica", "Burger del mes", "Cheddar plancha", "La limeña"],
    answer: "C",
    explanation: "El código B13 corresponde a Cheddar plancha.",
  },
  {
    id: "Q042",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B3?",
    options: ["Doble cuarto libra queso", "Cheddar plancha", "Clásica BBQ", "Burger Factory"],
    answer: "C",
    explanation: "El código B3 corresponde a Clásica BBQ.",
  },
  {
    id: "Q043",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B6?",
    options: ["Clásica BBQ", "BBQ tocino", "La limeña", "Burger completa"],
    answer: "B",
    explanation: "El código B6 corresponde a BBQ tocino.",
  },
  {
    id: "Q044",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B22?",
    options: ["Burger completa", "La 420", "Club Veggie", "Clásica BBQ"],
    answer: "C",
    explanation: "El código B22 corresponde a Club Veggie.",
  },
  {
    id: "Q045",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B16?",
    options: ["Kill Bill", "Burger básica", "Azul ruibarbo", "La limeña"],
    answer: "A",
    explanation: "El código B16 corresponde a Kill Bill.",
  },
  {
    id: "Q046",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B9?",
    options: ["Clásica BBQ", "Burger básica", "Doble cuarto libra queso", "Veggie Thai"],
    answer: "C",
    explanation: "El código B9 corresponde a Doble cuarto libra queso.",
  },
  {
    id: "Q047",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B17?",
    options: ["La gran S", "La tocinetta", "Los tres chanchitos", "Burger básica"],
    answer: "A",
    explanation: "El código B17 corresponde a La gran S.",
  },
  {
    id: "Q048",
    category: "Códigos Burgers",
    difficulty: "Fácil",
    question: "En la carta, ¿qué producto corresponde al código B2?",
    options: ["Nachos", "Burger completa", "Cheddar plancha", "BBQ tocino"],
    answer: "B",
    explanation: "El código B2 corresponde a Burger completa.",
  },
  {
    id: "Q049",
    category: "Burgers Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál de estas opciones es veggie de garbanzos?",
    options: ["La gran S", "La Francesa", "La 420", "Kill Bill"],
    answer: "C",
    explanation: "La respuesta correcta es La 420.",
  },
  {
    id: "Q050",
    category: "Burgers Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál burger incluye ceviche de camarón?",
    options: ["Camarones al limón", "Kill Bill", "Veggie Thai", "La limeña"],
    answer: "D",
    explanation: "La respuesta correcta es La limeña.",
  },
  {
    id: "Q051",
    category: "Burgers Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál burger incluye salsa BBQ con ruibarbo?",
    options: ["BBQ tocino", "La 36", "Clásica BBQ", "Azul ruibarbo"],
    answer: "D",
    explanation: "La respuesta correcta es Azul ruibarbo.",
  },
  {
    id: "Q052",
    category: "Burgers Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál burger incluye medallón de queso crocante?",
    options: ["Provoleta", "Cheddar plancha", "Doble cuarto libra queso", "Gouda frito"],
    answer: "C",
    explanation: "La respuesta correcta es Doble cuarto libra queso.",
  },
  {
    id: "Q053",
    category: "Burgers Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál producto permite elegir base, salsa y extras?",
    options: ["Burger del mes", "Burger Factory", "Burger básica", "Club Veggie"],
    answer: "B",
    explanation: "La respuesta correcta es Burger Factory.",
  },
  {
    id: "Q054",
    category: "Burgers Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál burger incluye tortilla de maíz?",
    options: ["Nachos", "La limeña", "La 420", "Veggie Thai"],
    answer: "B",
    explanation: "La respuesta correcta es La limeña.",
  },
  {
    id: "Q055",
    category: "Burgers Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál burger incluye salsa club?",
    options: ["La Francesa", "La 36", "Club Veggie", "Clásica BBQ"],
    answer: "C",
    explanation: "La respuesta correcta es Club Veggie.",
  },
  {
    id: "Q056",
    category: "Burgers Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál burger destaca por camarones envueltos en tocino?",
    options: ["Camarones al limón", "Papas Hattori Hanzō", "Kill Bill", "La limeña"],
    answer: "C",
    explanation: "La respuesta correcta es Kill Bill.",
  },
  {
    id: "Q057",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K1?",
    options: ["Aros de cebolla apanados con salsa (BBQ/Cheddar/Mostaza miel) (15u.)", "Papas fritas provenzal / rústicas + ajo + perejil", "Aros de cebolla apanados (15u.)", "Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (5u.)"],
    answer: "C",
    explanation: "El código K1 corresponde a Aros de cebolla apanados (15u.).",
  },
  {
    id: "Q058",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K2?",
    options: ["Mix bastones de muzzarella + aros de cebolla + papas", "Papas fritas con camarones a la parmesana", "Papas fritas con salsa cheddar + tocino chips + pepinillos agridulces", "Aros de cebolla apanados con salsa (BBQ/Cheddar/Mostaza miel) (15u.)"],
    answer: "D",
    explanation: "El código K2 corresponde a Aros de cebolla apanados con salsa (BBQ/Cheddar/Mostaza miel) (15u.).",
  },
  {
    id: "Q059",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K3?",
    options: ["Bastones de muzzarella apanados (10u.)", "Papas fritas con dos huevos fritos o revueltos", "Aros de cebolla apanados con salsa (BBQ/Cheddar/Mostaza miel) (15u.)", "Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (10u.)"],
    answer: "A",
    explanation: "El código K3 corresponde a Bastones de muzzarella apanados (10u.).",
  },
  {
    id: "Q060",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K4?",
    options: ["Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (5u.)", "Papas fritas con dos huevos fritos o revueltos", "Aros de cebolla apanados (15u.)", "Bastones de muzzarella apanados con salsa BBQ (10u.)"],
    answer: "D",
    explanation: "El código K4 corresponde a Bastones de muzzarella apanados con salsa BBQ (10u.).",
  },
  {
    id: "Q061",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K5?",
    options: ["Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (5u.)", "Mix bastones de muzzarella + aros de cebolla + papas", "Papas fritas con longaniza ahumada de cerdo + dos huevos", "Papas fritas con salsa cheddar + tocino chips + pepinillos agridulces"],
    answer: "A",
    explanation: "El código K5 corresponde a Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (5u.).",
  },
  {
    id: "Q062",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K6?",
    options: ["Mix papas fritas rústicas + aros de cebolla apanados", "Papas fritas con longaniza ahumada de cerdo + dos huevos", "Papas fritas mix de ajíes + salsa sriracha", "Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (10u.)"],
    answer: "D",
    explanation: "El código K6 corresponde a Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (10u.).",
  },
  {
    id: "Q063",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K7?",
    options: ["Papas Hattori Hanzō con camarones envueltos en tocino, queso crema y salsa ginzoo", "Papas fritas rústicas", "Papas fritas con camarones al limón + palta trozada", "Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito"],
    answer: "B",
    explanation: "El código K7 corresponde a Papas fritas rústicas.",
  },
  {
    id: "Q064",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K8?",
    options: ["Papas fritas con salsa cheddar + tocino chips + pepinillos agridulces", "Aros de cebolla apanados con salsa (BBQ/Cheddar/Mostaza miel) (15u.)", "Mix papas fritas rústicas + aros de cebolla apanados", "Papas fritas mix de ajíes + salsa sriracha"],
    answer: "C",
    explanation: "El código K8 corresponde a Mix papas fritas rústicas + aros de cebolla apanados.",
  },
  {
    id: "Q065",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K9?",
    options: ["Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito", "Aros de cebolla apanados (15u.)", "Mix bastones de muzzarella + aros de cebolla + papas", "Papas fritas con salsa cheddar + tocino chips + pepinillos agridulces"],
    answer: "C",
    explanation: "El código K9 corresponde a Mix bastones de muzzarella + aros de cebolla + papas.",
  },
  {
    id: "Q066",
    category: "Snacks",
    difficulty: "Fácil",
    question: "¿Qué snack corresponde al código K10?",
    options: ["Papas fritas provenzal / rústicas + ajo + perejil", "Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (5u.)", "Bastones de muzzarella apanados (10u.)", "Papas fritas con salsa cheddar + tocino chips + pepinillos agridulces"],
    answer: "A",
    explanation: "El código K10 corresponde a Papas fritas provenzal / rústicas + ajo + perejil.",
  },
  {
    id: "Q067",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Papas fritas rústicas?",
    options: ["$6.200", "$6.500", "$9.200", "$5.500"],
    answer: "D",
    explanation: "Papas fritas rústicas aparece en la carta con precio $5.500.",
  },
  {
    id: "Q068",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Papas fritas con camarones a la vasca?",
    options: ["$5.000", "$6.200", "$9.500", "$5.500"],
    answer: "C",
    explanation: "Papas fritas con camarones a la vasca aparece en la carta con precio $9.500.",
  },
  {
    id: "Q069",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Papas fritas con dos huevos fritos o revueltos?",
    options: ["$6.800", "$5.000", "$7.000", "$6.000"],
    answer: "D",
    explanation: "Papas fritas con dos huevos fritos o revueltos aparece en la carta con precio $6.000.",
  },
  {
    id: "Q070",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Bastones de muzzarella apanados (10u.)?",
    options: ["$7.000", "$6.800", "$7.200", "$10.500"],
    answer: "A",
    explanation: "Bastones de muzzarella apanados (10u.) aparece en la carta con precio $7.000.",
  },
  {
    id: "Q071",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Aros de cebolla apanados (15u.)?",
    options: ["$8.200", "$5.500", "$7.500", "$7.000"],
    answer: "B",
    explanation: "Aros de cebolla apanados (15u.) aparece en la carta con precio $5.500.",
  },
  {
    id: "Q072",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito?",
    options: ["$9.200", "$5.000", "$10.500", "$6.000"],
    answer: "C",
    explanation: "Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito aparece en la carta con precio $10.500.",
  },
  {
    id: "Q073",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Mix bastones de muzzarella + aros de cebolla + papas?",
    options: ["$7.200", "$10.500", "$9.500", "$5.500"],
    answer: "A",
    explanation: "Mix bastones de muzzarella + aros de cebolla + papas aparece en la carta con precio $7.200.",
  },
  {
    id: "Q074",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Papas Hattori Hanzō con camarones envueltos en tocino, queso crema y salsa ginzoo?",
    options: ["$7.000", "$6.000", "$9.500", "$5.000"],
    answer: "C",
    explanation: "Papas Hattori Hanzō con camarones envueltos en tocino, queso crema y salsa ginzoo aparece en la carta con precio $9.500.",
  },
  {
    id: "Q075",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Mix papas fritas rústicas + aros de cebolla apanados?",
    options: ["$10.500", "$5.500", "$8.200", "$6.500"],
    answer: "B",
    explanation: "Mix papas fritas rústicas + aros de cebolla apanados aparece en la carta con precio $5.500.",
  },
  {
    id: "Q076",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Bastones de muzzarella apanados con salsa BBQ (10u.)?",
    options: ["$7.000", "$6.800", "$10.500", "$7.500"],
    answer: "D",
    explanation: "Bastones de muzzarella apanados con salsa BBQ (10u.) aparece en la carta con precio $7.500.",
  },
  {
    id: "Q077",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (10u.)?",
    options: ["$8.800", "$9.200", "$9.500", "$7.000"],
    answer: "B",
    explanation: "Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (10u.) aparece en la carta con precio $9.200.",
  },
  {
    id: "Q078",
    category: "Precios Snacks",
    difficulty: "Media",
    question: "¿Cuál es el precio de Papas fritas mix de ajíes + salsa sriracha?",
    options: ["$7.500", "$6.200", "$8.200", "$6.500"],
    answer: "B",
    explanation: "Papas fritas mix de ajíes + salsa sriracha aparece en la carta con precio $6.200.",
  },
  {
    id: "Q079",
    category: "Snacks Especiales",
    difficulty: "Media/Alta",
    question: "¿Qué snack incluye salsa cheddar, tocino chips y pepinillos agridulces?",
    options: ["Papas fritas con queso crema + tocino chips", "Papas fritas provenzal / rústicas + ajo + perejil", "Papas fritas con salsa cheddar + tocino chips + pepinillos agridulces", "Mix papas fritas rústicas + aros de cebolla apanados"],
    answer: "C",
    explanation: "La respuesta correcta es Papas fritas con salsa cheddar + tocino chips + pepinillos agridulces.",
  },
  {
    id: "Q080",
    category: "Snacks Especiales",
    difficulty: "Media/Alta",
    question: "¿Qué snack incluye longaniza ahumada de cerdo y dos huevos?",
    options: ["Papas fritas con dos huevos fritos o revueltos", "Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito", "Papas fritas con longaniza ahumada de cerdo + dos huevos", "Papas Hattori Hanzō con camarones envueltos en tocino, queso crema y salsa ginzoo"],
    answer: "C",
    explanation: "La respuesta correcta es Papas fritas con longaniza ahumada de cerdo + dos huevos.",
  },
  {
    id: "Q081",
    category: "Snacks Especiales",
    difficulty: "Media/Alta",
    question: "¿Qué snack incluye brisket ahumada, cebolla caramelizada y huevo frito?",
    options: ["Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito", "Papas fritas con queso crema + tocino chips", "Papas fritas con camarones a la vasca", "Papas fritas con salsa cheddar + tocino chips + pepinillos agridulces"],
    answer: "A",
    explanation: "La respuesta correcta es Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito.",
  },
  {
    id: "Q082",
    category: "Snacks Especiales",
    difficulty: "Media/Alta",
    question: "¿Qué snack incluye camarones envueltos en tocino, queso crema y salsa ginzoo?",
    options: ["Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (10u.)", "Papas fritas con camarones al limón + palta trozada", "Papas fritas con camarones a la parmesana", "Papas Hattori Hanzō con camarones envueltos en tocino, queso crema y salsa ginzoo"],
    answer: "D",
    explanation: "La respuesta correcta es Papas Hattori Hanzō con camarones envueltos en tocino, queso crema y salsa ginzoo.",
  },
  {
    id: "Q083",
    category: "Snacks Especiales",
    difficulty: "Media/Alta",
    question: "¿Qué snack combina bastones de muzzarella, aros de cebolla y papas?",
    options: ["Bastones de muzzarella apanados con salsa BBQ (10u.)", "Mix bastones de muzzarella + aros de cebolla + papas", "Mix papas fritas rústicas + aros de cebolla apanados", "Aros de cebolla apanados con salsa (BBQ/Cheddar/Mostaza miel) (15u.)"],
    answer: "B",
    explanation: "La respuesta correcta es Mix bastones de muzzarella + aros de cebolla + papas.",
  },
  {
    id: "Q084",
    category: "Snacks Especiales",
    difficulty: "Media/Alta",
    question: "¿Cuál snack son papas fritas con mix de ajíes y salsa sriracha?",
    options: ["Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (5u.)", "Papas fritas provenzal / rústicas + ajo + perejil", "Papas fritas con dos huevos fritos o revueltos", "Papas fritas mix de ajíes + salsa sriracha"],
    answer: "D",
    explanation: "La respuesta correcta es Papas fritas mix de ajíes + salsa sriracha.",
  },
  {
    id: "Q085",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S1?",
    options: ["Sandwich Philly", "TLT", "Matambre chimichurri", "QTH"],
    answer: "B",
    explanation: "El código S1 corresponde a TLT.",
  },
  {
    id: "Q086",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S2?",
    options: ["TLT", "THP", "Brisket ahumada cuatro quesos", "Sandwich Philly"],
    answer: "B",
    explanation: "El código S2 corresponde a THP.",
  },
  {
    id: "Q087",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S3?",
    options: ["QTH", "Harley Quinn", "TLT", "Matambre chimichurri"],
    answer: "A",
    explanation: "El código S3 corresponde a QTH.",
  },
  {
    id: "Q088",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S4?",
    options: ["Matambre chimichurri", "THP", "Brisket ahumada cuatro quesos", "Sandwich Philly"],
    answer: "A",
    explanation: "El código S4 corresponde a Matambre chimichurri.",
  },
  {
    id: "Q089",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S5?",
    options: ["Matambre a la parrilla", "Pulled Pork Gouda", "Matambre chimichurri", "TLT"],
    answer: "A",
    explanation: "El código S5 corresponde a Matambre a la parrilla.",
  },
  {
    id: "Q090",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S6?",
    options: ["THP", "Brisket ahumada cuatro quesos", "QTH", "TLT"],
    answer: "B",
    explanation: "El código S6 corresponde a Brisket ahumada cuatro quesos.",
  },
  {
    id: "Q091",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S7?",
    options: ["Pulled Pork Gouda", "Sandwich Philly", "Matambre a la parrilla", "Harley Quinn"],
    answer: "B",
    explanation: "El código S7 corresponde a Sandwich Philly.",
  },
  {
    id: "Q092",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S8?",
    options: ["THP", "Harley Quinn", "Sandwich Philly", "QTH"],
    answer: "B",
    explanation: "El código S8 corresponde a Harley Quinn.",
  },
  {
    id: "Q093",
    category: "Sándwiches",
    difficulty: "Fácil",
    question: "¿Qué sándwich corresponde al código S9?",
    options: ["Pulled Pork Gouda", "Matambre chimichurri", "THP", "Matambre a la parrilla"],
    answer: "A",
    explanation: "El código S9 corresponde a Pulled Pork Gouda.",
  },
  {
    id: "Q094",
    category: "Sándwiches",
    difficulty: "Media",
    question: "¿Qué sándwich viene en pan brioche con doble cheddar, doble huevo, tocino, salsa BBQ y sriracha?",
    options: ["TLT", "Harley Quinn", "Sandwich Philly", "QTH"],
    answer: "B",
    explanation: "La respuesta correcta es Harley Quinn.",
  },
  {
    id: "Q095",
    category: "Sándwiches",
    difficulty: "Media",
    question: "¿Qué sándwich incluye baguette de brisket ahumada y crocante de queso?",
    options: ["Matambre chimichurri", "Sandwich Philly", "Pulled Pork Gouda", "Brisket ahumada cuatro quesos"],
    answer: "B",
    explanation: "La respuesta correcta es Sandwich Philly.",
  },
  {
    id: "Q096",
    category: "Sándwiches",
    difficulty: "Media",
    question: "¿Qué sándwich incluye matambre tiernizado a la parrilla, queso gouda y chimichurri?",
    options: ["TLT", "Matambre chimichurri", "Matambre a la parrilla", "THP"],
    answer: "B",
    explanation: "La respuesta correcta es Matambre chimichurri.",
  },
  {
    id: "Q097",
    category: "Sándwiches",
    difficulty: "Media",
    question: "¿Qué sándwich incluye pulled pork, queso gouda, pepinillos y huevo frito?",
    options: ["QTH", "Harley Quinn", "Pulled Pork Gouda", "Sandwich Philly"],
    answer: "C",
    explanation: "La respuesta correcta es Pulled Pork Gouda.",
  },
  {
    id: "Q098",
    category: "Sándwiches",
    difficulty: "Media",
    question: "¿Qué sándwich incluye tocino, huevo frito y palta trozada?",
    options: ["TLT", "THP", "QTH", "Matambre a la parrilla"],
    answer: "B",
    explanation: "La respuesta correcta es THP.",
  },
  {
    id: "Q099",
    category: "Precios Sándwiches",
    difficulty: "Media",
    question: "¿Cuál es el precio de Matambre a la parrilla?",
    options: ["$9.500", "$12.500", "$8.800", "$12.100"],
    answer: "B",
    explanation: "Matambre a la parrilla aparece en la carta con precio $12.500.",
  },
  {
    id: "Q100",
    category: "Precios Sándwiches",
    difficulty: "Media",
    question: "¿Cuál es el precio de Pulled Pork Gouda?",
    options: ["$9.200", "$11.800", "$10.500", "$9.900"],
    answer: "C",
    explanation: "Pulled Pork Gouda aparece en la carta con precio $10.500.",
  },
  {
    id: "Q101",
    category: "Precios Sándwiches",
    difficulty: "Media",
    question: "¿Cuál es el precio de QTH?",
    options: ["$9.900", "$11.800", "$12.500", "$8.200"],
    answer: "A",
    explanation: "QTH aparece en la carta con precio $9.900.",
  },
  {
    id: "Q102",
    category: "Precios Sándwiches",
    difficulty: "Media",
    question: "¿Cuál es el precio de THP?",
    options: ["$10.500", "$11.800", "$9.900", "$9.200"],
    answer: "A",
    explanation: "THP aparece en la carta con precio $10.500.",
  },
  {
    id: "Q103",
    category: "Precios Sándwiches",
    difficulty: "Media",
    question: "¿Cuál es el precio de TLT?",
    options: ["$9.200", "$11.800", "$9.900", "$12.100"],
    answer: "A",
    explanation: "TLT aparece en la carta con precio $9.200.",
  },
  {
    id: "Q104",
    category: "Precios Sándwiches",
    difficulty: "Media",
    question: "¿Cuál es el precio de Brisket ahumada cuatro quesos?",
    options: ["$12.500", "$8.800", "$9.500", "$9.200"],
    answer: "A",
    explanation: "Brisket ahumada cuatro quesos aparece en la carta con precio $12.500.",
  },
  {
    id: "Q105",
    category: "Extras",
    difficulty: "Media",
    question: "¿A qué categoría pertenece Brisket ahumada como extra?",
    options: ["Quesos", "Verduras", "Carnes", "Salsas Premium"],
    answer: "C",
    explanation: "La respuesta correcta es Carnes.",
  },
  {
    id: "Q106",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál es el precio de Brisket ahumada como extra?",
    options: ["$3.200", "$4.800", "$2.500", "$3.600"],
    answer: "A",
    explanation: "La respuesta correcta es $3.200.",
  },
  {
    id: "Q107",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál es el precio de Camarones como extra?",
    options: ["$3.600", "$5.500", "$3.200", "$2.500"],
    answer: "A",
    explanation: "La respuesta correcta es $3.600.",
  },
  {
    id: "Q108",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál es el precio de Burger extra doble?",
    options: ["$3.200", "$4.800", "$3.600", "$5.500"],
    answer: "B",
    explanation: "La respuesta correcta es $4.800.",
  },
  {
    id: "Q109",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál es el precio de 4 quesos como extra?",
    options: ["$2.500", "$1.800", "$2.200", "$3.000"],
    answer: "D",
    explanation: "La respuesta correcta es $3.000.",
  },
  {
    id: "Q110",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál es el precio de Palta trozada como extra?",
    options: ["$2.500", "$2.000", "$1.500", "$3.000"],
    answer: "A",
    explanation: "La respuesta correcta es $2.500.",
  },
  {
    id: "Q111",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál de estos pertenece a Salsas Premium?",
    options: ["Cheddar / Gouda / Parmesano", "BBQ / Club / Mostaza miel", "Mayonesa / Ketchup / Mostaza", "Pepinillos / Tomate / Lechuga"],
    answer: "B",
    explanation: "La respuesta correcta es BBQ / Club / Mostaza miel.",
  },
  {
    id: "Q112",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál es el precio de las Salsas Base?",
    options: ["$1.000", "$800", "$1.500", "$2.000"],
    answer: "B",
    explanation: "La respuesta correcta es $800.",
  },
  {
    id: "Q113",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál es el precio de las Salsas Premium?",
    options: ["$800", "$2.000", "$1.500", "$1.000"],
    answer: "D",
    explanation: "La respuesta correcta es $1.000.",
  },
  {
    id: "Q114",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál de estos extras tiene precio $1.200?",
    options: ["Aros de cebolla", "Camarones", "Palta trozada", "Mix de ajíes"],
    answer: "A",
    explanation: "La respuesta correcta es Aros de cebolla.",
  },
  {
    id: "Q115",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál de estos extras tiene precio $2.000?",
    options: ["Aros de cebolla", "Cebollín", "Morrones", "Mix de ajíes"],
    answer: "D",
    explanation: "La respuesta correcta es Mix de ajíes.",
  },
  {
    id: "Q116",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál de estos extras cuesta $5.500?",
    options: ["4 quesos", "Camarones", "Burger extra doble", "Camarón Kill Bill (Snack)"],
    answer: "D",
    explanation: "La respuesta correcta es Camarón Kill Bill (Snack).",
  },
  {
    id: "Q117",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál categoría incluye Tocino, Longaniza ahumada de cerdo y Pulled pork?",
    options: ["Carnes", "Salsas Base", "Quesos", "Verduras"],
    answer: "A",
    explanation: "La respuesta correcta es Carnes.",
  },
  {
    id: "Q118",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál categoría incluye Pepinillos, Tomate, Lechuga y Cebolla?",
    options: ["Salsas Premium", "Verduras", "Carnes", "Quesos"],
    answer: "B",
    explanation: "La respuesta correcta es Verduras.",
  },
  {
    id: "Q119",
    category: "Extras",
    difficulty: "Media",
    question: "¿Cuál categoría incluye Cheddar, Gouda, Parmesano y Queso crema?",
    options: ["Carnes", "Quesos", "Salsas Base", "Verduras"],
    answer: "B",
    explanation: "La respuesta correcta es Quesos.",
  },
  {
    id: "Q120",
    category: "Postres",
    difficulty: "Fácil",
    question: "¿Qué postre es una bola de helado de vainilla ahogada en espresso?",
    options: ["Copa de helado", "Donuts con helado y salsa de chocolate", "Brownie con helado y salsa de chocolate", "Affogato"],
    answer: "D",
    explanation: "La respuesta correcta es Affogato.",
  },
  {
    id: "Q121",
    category: "Postres",
    difficulty: "Fácil",
    question: "¿Cuál es el precio del Affogato?",
    options: ["$6.000", "$4.500", "$7.000", "$5.500"],
    answer: "B",
    explanation: "La respuesta correcta es $4.500.",
  },
  {
    id: "Q122",
    category: "Postres",
    difficulty: "Fácil",
    question: "¿Cuál de estos productos pertenece a Postres?",
    options: ["Brownie con helado y salsa de chocolate", "Papas fritas rústicas", "Burger básica", "TLT"],
    answer: "A",
    explanation: "La respuesta correcta es Brownie con helado y salsa de chocolate.",
  },
  {
    id: "Q123",
    category: "Postres",
    difficulty: "Fácil",
    question: "¿Cuál de estos productos pertenece a Postres?",
    options: ["Cóndor wings", "Burger Factory", "Donuts con helado y salsa de chocolate", "Kill Bill"],
    answer: "C",
    explanation: "La respuesta correcta es Donuts con helado y salsa de chocolate.",
  },
  {
    id: "Q124",
    category: "Postres",
    difficulty: "Fácil",
    question: "¿Qué postre aparece con precio $4.500?",
    options: ["Copa de helado", "Burger básica", "Aros de cebolla apanados", "Papas fritas rústicas"],
    answer: "A",
    explanation: "La respuesta correcta es Copa de helado.",
  },
  {
    id: "Q125",
    category: "Postres",
    difficulty: "Fácil",
    question: "¿Cuáles postres de la carta están a $4.500?",
    options: ["Solo Brownie", "Ninguno", "Todos los postres listados", "Solo Affogato"],
    answer: "C",
    explanation: "La respuesta correcta es Todos los postres listados.",
  },
  {
    id: "Q126",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: La 420 es una burger veggie de garbanzos.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q127",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Kill Bill incluye camarones envueltos en tocino.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q128",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: La limeña incluye ceviche de camarón.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q129",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: La tocinetta incluye chocobacon y tocinesa.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q130",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: La Francesa incluye camarones al limón.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "B",
    explanation: "La afirmación es falso según la carta.",
  },
  {
    id: "Q131",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Burger Factory tiene base, salsa y extras a elección.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q132",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Papas Hattori Hanzō incluyen camarones envueltos en tocino, queso crema y salsa ginzoo.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q133",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: El Affogato es una bola de helado de vainilla ahogada en espresso.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q134",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: La Burger básica cuesta $13.600.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "B",
    explanation: "La afirmación es falso según la carta.",
  },
  {
    id: "Q135",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Doble cuarto libra queso cuesta $13.600.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q136",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Harley Quinn viene en pan brioche.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q137",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: El snack K20 corresponde a Papas Hattori Hanzō.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q138",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Las Salsas Premium cuestan $800.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "B",
    explanation: "La afirmación es falso según la carta.",
  },
  {
    id: "Q139",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Las Salsas Base cuestan $800.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q140",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Brisket ahumada como extra cuesta $3.200.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "A",
    explanation: "La afirmación es verdadero según la carta.",
  },
  {
    id: "Q141",
    category: "Verdadero/Falso",
    difficulty: "Fácil/Media",
    question: "Verdadero o falso: Camarones como extra cuestan $1.500.",
    options: ["Verdadero", "Falso", "Depende del local", "No aparece en la carta"],
    answer: "B",
    explanation: "La afirmación es falso según la carta.",
  },
  {
    id: "Q142",
    category: "Preguntas Premium",
    difficulty: "Alta",
    question: "¿Cuál es la burger de mayor precio entre estas opciones?",
    options: ["Doble cuarto libra queso", "Provoleta", "Kill Bill", "Los tres chanchitos"],
    answer: "A",
    explanation: "La respuesta correcta es Doble cuarto libra queso.",
  },
  {
    id: "Q143",
    category: "Preguntas Premium",
    difficulty: "Alta",
    question: "¿Cuál de estas burgers cuesta $12.800?",
    options: ["Kill Bill", "Provoleta", "La gran S", "Los tres chanchitos"],
    answer: "A",
    explanation: "La respuesta correcta es Kill Bill.",
  },
  {
    id: "Q144",
    category: "Preguntas Premium",
    difficulty: "Alta",
    question: "¿Cuál de estas opciones cuesta $6.700?",
    options: ["Club Veggie", "Burger básica", "La 420", "Burger Factory"],
    answer: "D",
    explanation: "La respuesta correcta es Burger Factory.",
  },
  {
    id: "Q145",
    category: "Preguntas Premium",
    difficulty: "Alta",
    question: "¿Cuál de estas burgers cuesta $9.500?",
    options: ["Azul ruibarbo", "Burger completa", "Nachos", "La 420"],
    answer: "D",
    explanation: "La respuesta correcta es La 420.",
  },
  {
    id: "Q146",
    category: "Preguntas Premium",
    difficulty: "Alta",
    question: "¿Cuál de estas burgers cuesta $10.800?",
    options: ["BBQ tocino", "Gouda frito", "La tocinetta", "Clásica BBQ"],
    answer: "C",
    explanation: "La respuesta correcta es La tocinetta.",
  },
  {
    id: "Q147",
    category: "Preguntas Premium",
    difficulty: "Alta",
    question: "¿Cuál snack cuesta $10.500?",
    options: ["Cóndor wings + salsa (mostaza miel/BBQ/club/sriracha) (10u.)", "Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito", "Papas fritas con camarones a la parmesana", "Papas Hattori Hanzō con camarones envueltos en tocino, queso crema y salsa ginzoo"],
    answer: "B",
    explanation: "La respuesta correcta es Papas fritas con brisket ahumada, cebolla caramelizada + huevo frito.",
  },
  {
    id: "Q148",
    category: "Preguntas Premium",
    difficulty: "Alta",
    question: "¿Cuál sándwich cuesta $8.800?",
    options: ["Harley Quinn", "TLT", "QTH", "THP"],
    answer: "A",
    explanation: "La respuesta correcta es Harley Quinn.",
  },
  {
    id: "Q149",
    category: "Preguntas Premium",
    difficulty: "Alta",
    question: "¿Qué producto tiene precio variable o sin precio fijo indicado?",
    options: ["Burger básica", "Burger Factory", "Burger del mes", "Veggie Thai"],
    answer: "C",
    explanation: "La respuesta correcta es Burger del mes.",
  },
  {
    id: "Q150",
    category: "Banco Completo",
    difficulty: "Media/Alta",
    question: "¿Cuál burger combina queso cheddar, tocino, palta trozada y huevo frito?",
    options: ["Cheddar plancha", "La gran S", "Clásica BBQ", "Gouda frito"],
    answer: "B",
    explanation: "La respuesta correcta es La gran S.",
  },
];
